version: '3.8'

services:
  pet-store:
    build: ./
    command: ./wait-for-postgres.sh db ./pet-store
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    networks:
      - my_network

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - my_network

networks:
  my_network:
    driver: bridge